"""drop_block_est_duration_ms

Revision ID: 387ab1650d59
Revises: 7e9cb0dba78a
Create Date: 2026-02-04 00:37:11.537808

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "387ab1650d59"
down_revision: str | None = "7e9cb0dba78a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("block", "est_duration_ms")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("block", sa.Column("est_duration_ms", sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
